# Generated by Django 5.0.4 on 2024-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
