# Generated by Django 5.0.4 on 2024-04-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_blooddonate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
