# Generated by Django 5.0.4 on 2024-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_allrequestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrequestinfo',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
