# Generated by Django 5.0.4 on 2024-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_bloodrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
