# Generated by Django 5.0.4 on 2024-04-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregister',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hospitalregister',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
